name: Build

on:
  push:
    branches:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo token ${{ secrets.GITHUB_TOKEN }} | base64

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'

      - uses: actions/cache@v4
        with:
          path: /home/runner/go/pkg/mod
          key: my-go-mod
#
#      - uses: goreleaser/goreleaser-action@v6
#        with:
#          args: release --snapshot --skip sign

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}