name: Build

on:
  push:
    branches:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release --snapshot --skip sign

      - uses: actions/upload-artifact@v4
        with:
          name: yotoy_Darwin_arm64
          path: dist/yotoy_darwin_arm64/yotoy
          retention-days: 7