name: Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
